### ISSUE TITLE
ContinuousBuzzer tone stopping

### ISSUE THREAD

**Issue by Naxomiun** [m-abboud/android-tone-player#1]
No matter if you pause the thread, or set pause intervals. The tone will stop in a few seconds.
OneTimeBuffer is working well.

**Comment by m-abboud** [comment]
What device or emulator are you running into this issue on?

And what's your code look like? There's a pause every x seconds setting for the continuous buzzer that you might have copied from the example code.

**Comment by Naxomiun** [comment]
It seems to work fine right now with the same piece of code. Must have been something related with the device I was using in that moment. Sorry for the inconvenience.
