### ISSUE TITLE
Why LGPL? Why Not Apache 2.0?

### ISSUE THREAD

**Issue by motornyimaksym** [m-abboud/android-tone-player#4]
I want to use this library in my project but can't because I don't want to share my source codes but according to LGPL I should. Is it possible to make it Apache 2.0?

**Comment by m-abboud** [comment]
LGPL is way diffrent from GPL, you do not have to share source code for LGPL you just have to include the license somewhere in the documentation if you redistribute

**Comment by m-abboud** [comment]
99% certain you're fine with LGPL for commercial use and you're mistaking it for GPL or AGPL so I'm closing this (and I don't even care if you put the license in the documentation or readme and no  sinister GPL police force is going to be knocking on your door if you don't)
